export const TOOLTIPS = {
  SCANNER: {
    TIMEFRAME: "Historical lookback period for technical analysis. 1d = daily candles for swing trades.",
    LOOKBACK: "Number of days of price history to analyze. More data = better trend detection.",
    TOP_SET: "Maximum number of stocks to show in results. Top-ranked opportunities appear first.",
    TOTAL_SCANNED: "Total stocks checked from Nifty 500 universe this scan.",
    DATA_VALID: "Stocks with clean price history and sufficient volume for analysis.",
    BROAD_TREND: "Stocks passing initial trend filters (uptrend + momentum alignment).",
    SHORTLISTED: "High-confidence setups moved to deeper technical + backtest validation.",
    BUY_CANDIDATES: "Final BUY recommendations — strong technical + execution + backtest edge.",
    WATCH_CANDIDATES: "Promising setups needing clearer confirmation before entry.",
    REJECTED: "Stocks that failed trend, momentum, or risk/reward criteria.",
    SIGNAL_FILTER: "Filter by recommendation type: BUY (actionable), WATCH (monitor), REJECT (avoid).",
    SCORE_MIN: "Minimum composite score (0-100). Higher = stronger technical + fundamental confluence.",
    SCORE_MAX: "Maximum composite score. Use to focus on mid-tier setups if avoiding overextended stocks.",
    CONFIDENCE_CHECKBOX: "Show only high-confidence setups (78%+ technical alignment).",
    ENTRY_PRICE: "Suggested buy price range based on support levels and recent consolidation.",
    STOP_LOSS: "Exit price if trade moves against you — limits downside risk.",
    TARGET_1: "First profit target — book partial position here.",
    TARGET_2: "Final profit target — exit remaining position.",
    RISK_REWARD: "Reward-to-risk ratio (R:R). 1.27 means ₹1.27 potential profit per ₹1 risked.",
    TREND: "Price direction over lookback period: uptrend, downtrend, or sideways.",
    MOMENTUM: "Short-term price strength: supported (bullish) or fading (weakening).",
    VOLUME: "Trading activity: expanding (interest growing) or contracting.",
    NEWS: "Recent news sentiment: positive, neutral, or negative.",
  },

  PAPER_TRADING: {
    BALANCE: "Cash available to place new buy orders. Does not include value of open positions.",
    EQUITY: "Total account value = Cash + Market value of all open positions.",
    REALIZED_PNL: "Profit/loss from closed trades (booked gains/losses).",
    UNREALIZED_PNL: "Current profit/loss on open positions (not yet booked).",
    INVESTED: "Total capital locked in open positions at entry prices.",
    AVAILABLE_CASH: "Cash balance minus pending buy order reservations.",
    OPEN_POSITIONS: "Number of stocks currently held in the portfolio.",
    DAILY_PNL: "Today's profit/loss from closed trades (resets at market open).",
    TOTAL_PNL: "Cumulative P&L: Realized + Unrealized.",
    MARKET_STATUS: "Current NSE status: PRE-OPEN 🟡, OPEN 🟢, or CLOSED 🔴.",
    SQUARE_OFF_ALL: "Close all open positions at current market price immediately.",
    ORDER_TYPE: "LIMIT = buy at specific price. MARKET = buy at current price instantly.",
    PRODUCT_TYPE: "CNC = Cash and Carry (delivery). MIS = Intraday (must square-off same day).",
    QUANTITY: "Number of shares to buy. Use 'suggested qty' for risk-based position sizing.",
    LIMIT_PRICE: "Your maximum buy price for LIMIT orders. Order fills only if market reaches this price.",
    STOP_LOSS_FIELD: "Automatic exit price if trade goes against you. Triggers a sell order.",
    TARGET_FIELD: "Automatic exit price when profit target is reached. Triggers a sell order.",
    TRAILING_STOP: "Dynamic stop-loss that moves up with price. E.g., 2% means stop adjusts to 2% below highest price.",
    CASH_ALLOCATION: "Max % of account balance to risk on this trade (default 10%).",
    SUGGESTED_QTY: "Position size calculated from: (Cash × Allocation%) ÷ Entry Price.",
    AVG_ENTRY: "Average price paid for this position (if bought in multiple lots).",
    CURRENT_PRICE: "Live market price (fetched from FYERS or latest candle close).",
    UNREALIZED_COL: "Current profit/loss on this position = (Current - Entry) × Qty.",
    PERCENT_PNL: "Unrealized P&L as a percentage of invested capital.",
    STOP_COL: "Your set stop-loss price. Position auto-exits if market hits this level.",
    TARGET_COL: "Your profit target price. Position auto-exits when reached.",
    RR_COL: "Risk/Reward ratio for this position = (Target - Entry) ÷ (Entry - Stop).",
    WIN_RATE: "Percentage of closed trades that were profitable.",
    PROFIT_FACTOR: "Ratio of total wins to total losses. >1 = net profitable system.",
    BEST_TRADE: "Largest single-trade profit in account history.",
    WORST_TRADE: "Largest single-trade loss in account history.",
    AVG_PROFIT: "Average P&L per closed trade (wins + losses combined).",
    AVG_HOLD_PERIOD: "Average time (minutes/hours) positions are held before exit.",
  },

  ALERTS: {
    SYMBOL_FIELD: "Stock symbol to watch (e.g., RELIANCE-EQ).",
    CONDITION: "Price >= (alert when price rises above) or Price <= (alert when price falls below).",
    TARGET_PRICE: "Alert triggers when market price crosses this level.",
    CREATE_ALERT: "Set a price notification. You'll see a banner when the alert triggers.",
  },

  ANALYTICS: {
    CLOSED_TRADES: "Total number of completed trades (positions that were exited).",
    CUMULATIVE_PNL_CHART: "Running total of P&L over time. Shows equity curve growth/drawdown.",
    PNL_DISTRIBUTION: "Pie chart showing wins (green) vs losses (red) as % of total trades.",
  },
};

export default TOOLTIPS;
