"""Add last_reconciled_at to PaperPosition

Revision ID: 303dcf639306
Revises: 761f3802942c
Create Date: 2026-06-18 17:09:25.975001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303dcf639306'
down_revision: Union[str, Sequence[str], None] = '761f3802942c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_trading_positions', sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('paper_trading_positions', sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scan_snapshots', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('scan_snapshots', sa.Column('error_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_snapshots', 'error_type')
    op.drop_column('scan_snapshots', 'status')
    op.drop_column('paper_trading_positions', 'last_reconciled_at')
    op.drop_column('paper_trading_positions', 'last_evaluated_at')
    # ### end Alembic commands ###
