"""Add stocks_master table

Revision ID: 53fddb49fce8
Revises: a05c3df8d52e
Create Date: 2026-06-22 18:10:25.272218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53fddb49fce8'
down_revision: Union[str, Sequence[str], None] = 'a05c3df8d52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('series', sa.String(length=16), nullable=True),
    sa.Column('isin', sa.String(length=32), nullable=True),
    sa.Column('universe', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks_master'))
    )
    op.create_index(op.f('ix_stocks_master_id'), 'stocks_master', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_master_is_active'), 'stocks_master', ['is_active'], unique=False)
    op.create_index(op.f('ix_stocks_master_symbol'), 'stocks_master', ['symbol'], unique=True)
    op.create_index(op.f('ix_stocks_master_universe'), 'stocks_master', ['universe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_master_universe'), table_name='stocks_master')
    op.drop_index(op.f('ix_stocks_master_symbol'), table_name='stocks_master')
    op.drop_index(op.f('ix_stocks_master_is_active'), table_name='stocks_master')
    op.drop_index(op.f('ix_stocks_master_id'), table_name='stocks_master')
    op.drop_table('stocks_master')
    # ### end Alembic commands ###
