"""d3a3_foundation_completion

Revision ID: 6650a54dd6aa
Revises: 93945ca775e0
Create Date: 2026-05-29 14:34:02.932763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6650a54dd6aa'
down_revision: Union[str, Sequence[str], None] = '93945ca775e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_execution_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('previous_state', sa.String(length=32), nullable=True),
    sa.Column('new_state', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['live_orders.id'], name=op.f('fk_order_execution_events_order_id_live_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_execution_events'))
    )
    op.create_index(op.f('ix_order_execution_events_correlation_id'), 'order_execution_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_order_execution_events_event_timestamp'), 'order_execution_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_order_execution_events_event_type'), 'order_execution_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_order_execution_events_id'), 'order_execution_events', ['id'], unique=False)
    op.create_index(op.f('ix_order_execution_events_order_id'), 'order_execution_events', ['order_id'], unique=False)
    if op.get_bind().dialect.name != 'sqlite':
        op.create_foreign_key(op.f('fk_live_orders_account_id_live_accounts'), 'live_orders', 'live_accounts', ['account_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(op.f('fk_live_positions_account_id_live_accounts'), 'live_positions', 'live_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name != 'sqlite':
        op.drop_constraint(op.f('fk_live_positions_account_id_live_accounts'), 'live_positions', type_='foreignkey')
        op.drop_constraint(op.f('fk_live_orders_account_id_live_accounts'), 'live_orders', type_='foreignkey')
    op.drop_index(op.f('ix_order_execution_events_order_id'), table_name='order_execution_events')
    op.drop_index(op.f('ix_order_execution_events_id'), table_name='order_execution_events')
    op.drop_index(op.f('ix_order_execution_events_event_type'), table_name='order_execution_events')
    op.drop_index(op.f('ix_order_execution_events_event_timestamp'), table_name='order_execution_events')
    op.drop_index(op.f('ix_order_execution_events_correlation_id'), table_name='order_execution_events')
    op.drop_table('order_execution_events')
    # ### end Alembic commands ###
