"""remove_refresh_token

Revision ID: 7b6abc0bf8bc
Revises: beaf8450de15
Create Date: 2026-07-04 10:05:24.076246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6abc0bf8bc'
down_revision: Union[str, Sequence[str], None] = 'beaf8450de15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Remove legacy refresh token + auto-renewal columns.
    Uses IF EXISTS for safety in case columns were already removed manually
    or via prior recovery steps.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE fyers_tokens DROP COLUMN IF EXISTS refresh_token")
    op.execute("ALTER TABLE fyers_tokens DROP COLUMN IF EXISTS refresh_token_expires_at")
    op.execute("ALTER TABLE fyers_tokens DROP COLUMN IF EXISTS last_auto_renewal_at")
    op.execute("ALTER TABLE fyers_tokens DROP COLUMN IF EXISTS last_auto_renewal_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Re-add the columns that supported refresh token auto-renewal.
    # Note: data will be NULL after re-add; users would need to re-authenticate
    # for full refresh_token values.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fyers_tokens', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('fyers_tokens', sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fyers_tokens', sa.Column('last_auto_renewal_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fyers_tokens', sa.Column('last_auto_renewal_status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###
