"""baseline_schema

Revision ID: 7fa0ff0cccb8
Revises: 
Create Date: 2026-05-28 16:56:08.602361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa0ff0cccb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_request_logs'))
    )
    op.create_index(op.f('ix_api_request_logs_created_at'), 'api_request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_request_logs_id'), 'api_request_logs', ['id'], unique=False)
    op.create_table('blacklisted_symbols',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_blacklisted_symbols'))
    )
    op.create_index(op.f('ix_blacklisted_symbols_created_at'), 'blacklisted_symbols', ['created_at'], unique=False)
    op.create_table('dead_letter_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letter_jobs'))
    )
    op.create_index(op.f('ix_dead_letter_jobs_created_at'), 'dead_letter_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_dead_letter_jobs_id'), 'dead_letter_jobs', ['id'], unique=False)
    op.create_table('fyers_token_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_token_masked', sa.String(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fyers_token_history'))
    )
    op.create_table('fyers_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('access_token_saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fyers_tokens'))
    )
    op.create_index(op.f('ix_fyers_tokens_status'), 'fyers_tokens', ['status'], unique=False)
    op.create_table('historical_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historical_candles')),
    sa.UniqueConstraint('symbol', 'resolution', 'timestamp', name='uq_historical_candle')
    )
    op.create_index('idx_hist_candles_sym_res_ts', 'historical_candles', ['symbol', 'resolution', 'timestamp'], unique=False)
    op.create_index('idx_hist_candles_sym_ts', 'historical_candles', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_historical_candles_created_at'), 'historical_candles', ['created_at'], unique=False)
    op.create_index(op.f('ix_historical_candles_id'), 'historical_candles', ['id'], unique=False)
    op.create_index(op.f('ix_historical_candles_resolution'), 'historical_candles', ['resolution'], unique=False)
    op.create_index(op.f('ix_historical_candles_symbol'), 'historical_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_historical_candles_timestamp'), 'historical_candles', ['timestamp'], unique=False)
    op.create_index(op.f('ix_historical_candles_updated_at'), 'historical_candles', ['updated_at'], unique=False)
    op.create_table('latest_scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_latest_scan_results')),
    sa.UniqueConstraint('symbol', name=op.f('uq_latest_scan_results_symbol'))
    )
    op.create_index(op.f('ix_latest_scan_results_created_at'), 'latest_scan_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_latest_scan_results_id'), 'latest_scan_results', ['id'], unique=False)
    op.create_index(op.f('ix_latest_scan_results_scanned_at'), 'latest_scan_results', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_latest_scan_results_updated_at'), 'latest_scan_results', ['updated_at'], unique=False)
    op.create_table('market_engine_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tick_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('websocket_connected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('token_status', sa.String(length=32), nullable=False),
    sa.Column('paused_reason', sa.String(length=64), nullable=True),
    sa.Column('monitored_symbols_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_engine_sessions')),
    sa.UniqueConstraint('trading_date', name='uq_market_engine_session_trading_date')
    )
    op.create_index(op.f('ix_market_engine_sessions_created_at'), 'market_engine_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_engine_sessions_id'), 'market_engine_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_market_engine_sessions_status'), 'market_engine_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_market_engine_sessions_trading_date'), 'market_engine_sessions', ['trading_date'], unique=False)
    op.create_index(op.f('ix_market_engine_sessions_updated_at'), 'market_engine_sessions', ['updated_at'], unique=False)
    op.create_table('market_replay_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('replay_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('gap_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gap_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checkpoint_symbol', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_replay_sessions'))
    )
    op.create_index(op.f('ix_market_replay_sessions_created_at'), 'market_replay_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_replay_sessions_gap_end'), 'market_replay_sessions', ['gap_end'], unique=False)
    op.create_index(op.f('ix_market_replay_sessions_gap_start'), 'market_replay_sessions', ['gap_start'], unique=False)
    op.create_index(op.f('ix_market_replay_sessions_id'), 'market_replay_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_market_replay_sessions_replay_key'), 'market_replay_sessions', ['replay_key'], unique=True)
    op.create_index(op.f('ix_market_replay_sessions_started_at'), 'market_replay_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_market_replay_sessions_status'), 'market_replay_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_market_replay_sessions_updated_at'), 'market_replay_sessions', ['updated_at'], unique=False)
    op.create_table('paper_trading_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_risk_per_trade', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_trading_accounts'))
    )
    op.create_index(op.f('ix_paper_trading_accounts_created_at'), 'paper_trading_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_trading_accounts_id'), 'paper_trading_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_paper_trading_accounts_updated_at'), 'paper_trading_accounts', ['updated_at'], unique=False)
    op.create_table('paper_trading_execution_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_trading_execution_events')),
    sa.UniqueConstraint('dedupe_key', name='uq_execution_event_dedupe')
    )
    op.create_index('idx_execution_events_order_type', 'paper_trading_execution_events', ['order_id', 'event_type'], unique=False)
    op.create_index('idx_execution_events_position_type', 'paper_trading_execution_events', ['position_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_paper_trading_execution_events_created_at'), 'paper_trading_execution_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_trading_execution_events_dedupe_key'), 'paper_trading_execution_events', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_paper_trading_execution_events_event_id'), 'paper_trading_execution_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_paper_trading_execution_events_event_type'), 'paper_trading_execution_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_paper_trading_execution_events_id'), 'paper_trading_execution_events', ['id'], unique=False)
    op.create_index(op.f('ix_paper_trading_execution_events_order_id'), 'paper_trading_execution_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_paper_trading_execution_events_position_id'), 'paper_trading_execution_events', ['position_id'], unique=False)
    op.create_index(op.f('ix_paper_trading_execution_events_symbol'), 'paper_trading_execution_events', ['symbol'], unique=False)
    op.create_index(op.f('ix_paper_trading_execution_events_updated_at'), 'paper_trading_execution_events', ['updated_at'], unique=False)
    op.create_table('risk_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=24), nullable=False),
    sa.Column('default_position_size_pct', sa.Float(), nullable=False),
    sa.Column('max_risk_per_trade_pct', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_settings'))
    )
    op.create_index(op.f('ix_risk_settings_id'), 'risk_settings', ['id'], unique=False)
    op.create_table('saved_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('lookback_window', sa.Integer(), nullable=False),
    sa.Column('top_n', sa.Integer(), nullable=False),
    sa.Column('universe', sa.String(length=80), nullable=False),
    sa.Column('symbols_json', sa.Text(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_scans'))
    )
    op.create_index(op.f('ix_saved_scans_created_at'), 'saved_scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_scans_id'), 'saved_scans', ['id'], unique=False)
    op.create_index(op.f('ix_saved_scans_name'), 'saved_scans', ['name'], unique=True)
    op.create_index(op.f('ix_saved_scans_updated_at'), 'saved_scans', ['updated_at'], unique=False)
    op.create_table('scan_history_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_name', sa.String(length=120), nullable=False),
    sa.Column('screener_name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('lookback_window', sa.Integer(), nullable=False),
    sa.Column('top_n', sa.Integer(), nullable=False),
    sa.Column('universe', sa.String(length=80), nullable=False),
    sa.Column('scanned_symbols', sa.Integer(), nullable=False),
    sa.Column('shortlisted_count', sa.Integer(), nullable=False),
    sa.Column('buy_count', sa.Integer(), nullable=False),
    sa.Column('watch_count', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=80), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_history_snapshots'))
    )
    op.create_index(op.f('ix_scan_history_snapshots_created_at'), 'scan_history_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_history_snapshots_id'), 'scan_history_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_scan_history_snapshots_mode'), 'scan_history_snapshots', ['mode'], unique=False)
    op.create_index(op.f('ix_scan_history_snapshots_scan_name'), 'scan_history_snapshots', ['scan_name'], unique=False)
    op.create_index(op.f('ix_scan_history_snapshots_universe'), 'scan_history_snapshots', ['universe'], unique=False)
    op.create_table('scanned_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=25), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('screener_name', sa.String(length=100), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('technical_signal', sa.String(length=20), nullable=True),
    sa.Column('screener_score', sa.Float(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scanned_candidates'))
    )
    op.create_index(op.f('ix_scanned_candidates_id'), 'scanned_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_scanned_candidates_scanned_at'), 'scanned_candidates', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_scanned_candidates_symbol'), 'scanned_candidates', ['symbol'], unique=False)
    op.create_table('scanner_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('symbols_total', sa.Integer(), nullable=True),
    sa.Column('symbols_completed', sa.Integer(), nullable=True),
    sa.Column('symbols_failed', sa.Integer(), nullable=True),
    sa.Column('current_symbol', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_scanner_sessions'))
    )
    op.create_index(op.f('ix_scanner_sessions_created_at'), 'scanner_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_scanner_sessions_updated_at'), 'scanner_sessions', ['updated_at'], unique=False)
    op.create_table('service_health',
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('service_name', name=op.f('pk_service_health'))
    )
    op.create_index(op.f('ix_service_health_created_at'), 'service_health', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_health_updated_at'), 'service_health', ['updated_at'], unique=False)
    op.create_table('strategy_performance_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=25), nullable=False),
    sa.Column('screened_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_score', sa.Float(), nullable=False),
    sa.Column('dominant_agent', sa.String(length=50), nullable=False),
    sa.Column('realized_return_5d', sa.Float(), nullable=True),
    sa.Column('realized_return_10d', sa.Float(), nullable=True),
    sa.Column('realized_return_20d', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_performance_log'))
    )
    op.create_index(op.f('ix_strategy_performance_log_id'), 'strategy_performance_log', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_performance_log_screened_date'), 'strategy_performance_log', ['screened_date'], unique=False)
    op.create_index(op.f('ix_strategy_performance_log_symbol'), 'strategy_performance_log', ['symbol'], unique=False)
    op.create_table('system_locks',
    sa.Column('lock_name', sa.String(length=100), nullable=False),
    sa.Column('locked_by', sa.String(length=200), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('lock_name', name=op.f('pk_system_locks'))
    )
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('error_hash', sa.String(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('correlationId', sa.String(), nullable=True),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('orderId', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_logs'))
    )
    op.create_index(op.f('ix_system_logs_correlationId'), 'system_logs', ['correlationId'], unique=False)
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_environment'), 'system_logs', ['environment'], unique=False)
    op.create_index(op.f('ix_system_logs_error_hash'), 'system_logs', ['error_hash'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_module'), 'system_logs', ['module'], unique=False)
    op.create_index(op.f('ix_system_logs_orderId'), 'system_logs', ['orderId'], unique=False)
    op.create_index(op.f('ix_system_logs_source'), 'system_logs', ['source'], unique=False)
    op.create_index(op.f('ix_system_logs_symbol'), 'system_logs', ['symbol'], unique=False)
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_logs_userId'), 'system_logs', ['userId'], unique=False)
    op.create_table('watched_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watched_stocks'))
    )
    op.create_index(op.f('ix_watched_stocks_created_at'), 'watched_stocks', ['created_at'], unique=False)
    op.create_index(op.f('ix_watched_stocks_id'), 'watched_stocks', ['id'], unique=False)
    op.create_index(op.f('ix_watched_stocks_symbol'), 'watched_stocks', ['symbol'], unique=True)
    op.create_table('workstation_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('condition', sa.String(length=8), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('scan_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workstation_alerts'))
    )
    op.create_index(op.f('ix_workstation_alerts_alert_type'), 'workstation_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_workstation_alerts_created_at'), 'workstation_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_workstation_alerts_id'), 'workstation_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_workstation_alerts_name'), 'workstation_alerts', ['name'], unique=False)
    op.create_index(op.f('ix_workstation_alerts_status'), 'workstation_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_workstation_alerts_symbol'), 'workstation_alerts', ['symbol'], unique=False)
    op.create_index(op.f('ix_workstation_alerts_updated_at'), 'workstation_alerts', ['updated_at'], unique=False)
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('backtest_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=12), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], name=op.f('fk_analysis_history_stock_id_watched_stocks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_history'))
    )
    op.create_index(op.f('ix_analysis_history_created_at'), 'analysis_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_history_id'), 'analysis_history', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_history_mode'), 'analysis_history', ['mode'], unique=False)
    op.create_index(op.f('ix_analysis_history_recommendation'), 'analysis_history', ['recommendation'], unique=False)
    op.create_index(op.f('ix_analysis_history_stock_id'), 'analysis_history', ['stock_id'], unique=False)
    op.create_table('backtest_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('strategy_name', sa.String(length=80), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=False),
    sa.Column('cagr', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], name=op.f('fk_backtest_history_stock_id_watched_stocks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_history'))
    )
    op.create_index(op.f('ix_backtest_history_created_at'), 'backtest_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_history_id'), 'backtest_history', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_history_mode'), 'backtest_history', ['mode'], unique=False)
    op.create_index(op.f('ix_backtest_history_stock_id'), 'backtest_history', ['stock_id'], unique=False)
    op.create_table('paper_trading_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('condition', sa.String(length=4), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_trading_accounts.id'], name=op.f('fk_paper_trading_alerts_account_id_paper_trading_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_trading_alerts'))
    )
    op.create_index(op.f('ix_paper_trading_alerts_account_id'), 'paper_trading_alerts', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_trading_alerts_created_at'), 'paper_trading_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_trading_alerts_id'), 'paper_trading_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_paper_trading_alerts_status'), 'paper_trading_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_paper_trading_alerts_symbol'), 'paper_trading_alerts', ['symbol'], unique=False)
    op.create_index(op.f('ix_paper_trading_alerts_updated_at'), 'paper_trading_alerts', ['updated_at'], unique=False)
    op.create_table('paper_trading_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_trading_accounts.id'], name=op.f('fk_paper_trading_notifications_account_id_paper_trading_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_trading_notifications')),
    sa.UniqueConstraint('account_id', 'dedupe_key', name='uq_notification_account_dedupe')
    )
    op.create_index(op.f('ix_paper_trading_notifications_account_id'), 'paper_trading_notifications', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_trading_notifications_created_at'), 'paper_trading_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_trading_notifications_dedupe_key'), 'paper_trading_notifications', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_paper_trading_notifications_event_type'), 'paper_trading_notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_paper_trading_notifications_id'), 'paper_trading_notifications', ['id'], unique=False)
    op.create_table('paper_trading_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=12), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('product_type', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('order_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('target', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_entry_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('monitor_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('paused_reason', sa.String(length=64), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_ltp', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_signal', sa.String(length=16), nullable=True),
    sa.Column('source_score', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('source_confidence', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('filled_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_trading_accounts.id'], name=op.f('fk_paper_trading_orders_account_id_paper_trading_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_trading_orders'))
    )
    op.create_index('idx_orders_account_status_created', 'paper_trading_orders', ['account_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_orders_active_symbol', 'paper_trading_orders', ['symbol', 'status', 'lifecycle_state', 'monitor_enabled'], unique=False)
    op.create_index(op.f('ix_paper_trading_orders_account_id'), 'paper_trading_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_trading_orders_created_at'), 'paper_trading_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_trading_orders_id'), 'paper_trading_orders', ['id'], unique=False)
    op.create_index(op.f('ix_paper_trading_orders_idempotency_key'), 'paper_trading_orders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_paper_trading_orders_lifecycle_state'), 'paper_trading_orders', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_paper_trading_orders_order_type'), 'paper_trading_orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_paper_trading_orders_side'), 'paper_trading_orders', ['side'], unique=False)
    op.create_index(op.f('ix_paper_trading_orders_status'), 'paper_trading_orders', ['status'], unique=False)
    op.create_index(op.f('ix_paper_trading_orders_symbol'), 'paper_trading_orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_paper_trading_orders_updated_at'), 'paper_trading_orders', ['updated_at'], unique=False)
    op.create_table('paper_trading_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('target', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('monitor_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('paused_reason', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_signal', sa.String(length=16), nullable=True),
    sa.Column('source_score', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('source_confidence', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_trading_accounts.id'], name=op.f('fk_paper_trading_positions_account_id_paper_trading_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_trading_positions'))
    )
    op.create_index('idx_positions_active_symbol', 'paper_trading_positions', ['symbol', 'status', 'lifecycle_state', 'monitor_enabled'], unique=False)
    op.create_index('idx_unique_open_position', 'paper_trading_positions', ['account_id', 'symbol'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_index(op.f('ix_paper_trading_positions_account_id'), 'paper_trading_positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_trading_positions_created_at'), 'paper_trading_positions', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_trading_positions_id'), 'paper_trading_positions', ['id'], unique=False)
    op.create_index(op.f('ix_paper_trading_positions_lifecycle_state'), 'paper_trading_positions', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_paper_trading_positions_status'), 'paper_trading_positions', ['status'], unique=False)
    op.create_index(op.f('ix_paper_trading_positions_symbol'), 'paper_trading_positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_paper_trading_positions_updated_at'), 'paper_trading_positions', ['updated_at'], unique=False)
    op.create_table('paper_trading_trade_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pnl_percent', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_signal', sa.String(length=16), nullable=True),
    sa.Column('source_score', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('source_confidence', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_trading_accounts.id'], name=op.f('fk_paper_trading_trade_history_account_id_paper_trading_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_trading_trade_history'))
    )
    op.create_index(op.f('ix_paper_trading_trade_history_account_id'), 'paper_trading_trade_history', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_trading_trade_history_closed_at'), 'paper_trading_trade_history', ['closed_at'], unique=False)
    op.create_index(op.f('ix_paper_trading_trade_history_created_at'), 'paper_trading_trade_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_trading_trade_history_id'), 'paper_trading_trade_history', ['id'], unique=False)
    op.create_index(op.f('ix_paper_trading_trade_history_opened_at'), 'paper_trading_trade_history', ['opened_at'], unique=False)
    op.create_index(op.f('ix_paper_trading_trade_history_symbol'), 'paper_trading_trade_history', ['symbol'], unique=False)
    op.create_index(op.f('ix_paper_trading_trade_history_updated_at'), 'paper_trading_trade_history', ['updated_at'], unique=False)
    op.create_table('paper_trading_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_trading_accounts.id'], name=op.f('fk_paper_trading_transactions_account_id_paper_trading_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_trading_transactions'))
    )
    op.create_index(op.f('ix_paper_trading_transactions_account_id'), 'paper_trading_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_trading_transactions_action'), 'paper_trading_transactions', ['action'], unique=False)
    op.create_index(op.f('ix_paper_trading_transactions_id'), 'paper_trading_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_paper_trading_transactions_symbol'), 'paper_trading_transactions', ['symbol'], unique=False)
    op.create_index(op.f('ix_paper_trading_transactions_timestamp'), 'paper_trading_transactions', ['timestamp'], unique=False)
    op.create_table('scanner_symbol_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['scanner_sessions.session_id'], name=op.f('fk_scanner_symbol_tracking_session_id_scanner_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scanner_symbol_tracking')),
    sa.UniqueConstraint('session_id', 'symbol', name='uq_scanner_session_symbol')
    )
    op.create_index(op.f('ix_scanner_symbol_tracking_created_at'), 'scanner_symbol_tracking', ['created_at'], unique=False)
    op.create_index(op.f('ix_scanner_symbol_tracking_id'), 'scanner_symbol_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_scanner_symbol_tracking_updated_at'), 'scanner_symbol_tracking', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanner_symbol_tracking_updated_at'), table_name='scanner_symbol_tracking')
    op.drop_index(op.f('ix_scanner_symbol_tracking_id'), table_name='scanner_symbol_tracking')
    op.drop_index(op.f('ix_scanner_symbol_tracking_created_at'), table_name='scanner_symbol_tracking')
    op.drop_table('scanner_symbol_tracking')
    op.drop_index(op.f('ix_paper_trading_transactions_timestamp'), table_name='paper_trading_transactions')
    op.drop_index(op.f('ix_paper_trading_transactions_symbol'), table_name='paper_trading_transactions')
    op.drop_index(op.f('ix_paper_trading_transactions_id'), table_name='paper_trading_transactions')
    op.drop_index(op.f('ix_paper_trading_transactions_action'), table_name='paper_trading_transactions')
    op.drop_index(op.f('ix_paper_trading_transactions_account_id'), table_name='paper_trading_transactions')
    op.drop_table('paper_trading_transactions')
    op.drop_index(op.f('ix_paper_trading_trade_history_updated_at'), table_name='paper_trading_trade_history')
    op.drop_index(op.f('ix_paper_trading_trade_history_symbol'), table_name='paper_trading_trade_history')
    op.drop_index(op.f('ix_paper_trading_trade_history_opened_at'), table_name='paper_trading_trade_history')
    op.drop_index(op.f('ix_paper_trading_trade_history_id'), table_name='paper_trading_trade_history')
    op.drop_index(op.f('ix_paper_trading_trade_history_created_at'), table_name='paper_trading_trade_history')
    op.drop_index(op.f('ix_paper_trading_trade_history_closed_at'), table_name='paper_trading_trade_history')
    op.drop_index(op.f('ix_paper_trading_trade_history_account_id'), table_name='paper_trading_trade_history')
    op.drop_table('paper_trading_trade_history')
    op.drop_index(op.f('ix_paper_trading_positions_updated_at'), table_name='paper_trading_positions')
    op.drop_index(op.f('ix_paper_trading_positions_symbol'), table_name='paper_trading_positions')
    op.drop_index(op.f('ix_paper_trading_positions_status'), table_name='paper_trading_positions')
    op.drop_index(op.f('ix_paper_trading_positions_lifecycle_state'), table_name='paper_trading_positions')
    op.drop_index(op.f('ix_paper_trading_positions_id'), table_name='paper_trading_positions')
    op.drop_index(op.f('ix_paper_trading_positions_created_at'), table_name='paper_trading_positions')
    op.drop_index(op.f('ix_paper_trading_positions_account_id'), table_name='paper_trading_positions')
    op.drop_index('idx_unique_open_position', table_name='paper_trading_positions', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index('idx_positions_active_symbol', table_name='paper_trading_positions')
    op.drop_table('paper_trading_positions')
    op.drop_index(op.f('ix_paper_trading_orders_updated_at'), table_name='paper_trading_orders')
    op.drop_index(op.f('ix_paper_trading_orders_symbol'), table_name='paper_trading_orders')
    op.drop_index(op.f('ix_paper_trading_orders_status'), table_name='paper_trading_orders')
    op.drop_index(op.f('ix_paper_trading_orders_side'), table_name='paper_trading_orders')
    op.drop_index(op.f('ix_paper_trading_orders_order_type'), table_name='paper_trading_orders')
    op.drop_index(op.f('ix_paper_trading_orders_lifecycle_state'), table_name='paper_trading_orders')
    op.drop_index(op.f('ix_paper_trading_orders_idempotency_key'), table_name='paper_trading_orders')
    op.drop_index(op.f('ix_paper_trading_orders_id'), table_name='paper_trading_orders')
    op.drop_index(op.f('ix_paper_trading_orders_created_at'), table_name='paper_trading_orders')
    op.drop_index(op.f('ix_paper_trading_orders_account_id'), table_name='paper_trading_orders')
    op.drop_index('idx_orders_active_symbol', table_name='paper_trading_orders')
    op.drop_index('idx_orders_account_status_created', table_name='paper_trading_orders')
    op.drop_table('paper_trading_orders')
    op.drop_index(op.f('ix_paper_trading_notifications_id'), table_name='paper_trading_notifications')
    op.drop_index(op.f('ix_paper_trading_notifications_event_type'), table_name='paper_trading_notifications')
    op.drop_index(op.f('ix_paper_trading_notifications_dedupe_key'), table_name='paper_trading_notifications')
    op.drop_index(op.f('ix_paper_trading_notifications_created_at'), table_name='paper_trading_notifications')
    op.drop_index(op.f('ix_paper_trading_notifications_account_id'), table_name='paper_trading_notifications')
    op.drop_table('paper_trading_notifications')
    op.drop_index(op.f('ix_paper_trading_alerts_updated_at'), table_name='paper_trading_alerts')
    op.drop_index(op.f('ix_paper_trading_alerts_symbol'), table_name='paper_trading_alerts')
    op.drop_index(op.f('ix_paper_trading_alerts_status'), table_name='paper_trading_alerts')
    op.drop_index(op.f('ix_paper_trading_alerts_id'), table_name='paper_trading_alerts')
    op.drop_index(op.f('ix_paper_trading_alerts_created_at'), table_name='paper_trading_alerts')
    op.drop_index(op.f('ix_paper_trading_alerts_account_id'), table_name='paper_trading_alerts')
    op.drop_table('paper_trading_alerts')
    op.drop_index(op.f('ix_backtest_history_stock_id'), table_name='backtest_history')
    op.drop_index(op.f('ix_backtest_history_mode'), table_name='backtest_history')
    op.drop_index(op.f('ix_backtest_history_id'), table_name='backtest_history')
    op.drop_index(op.f('ix_backtest_history_created_at'), table_name='backtest_history')
    op.drop_table('backtest_history')
    op.drop_index(op.f('ix_analysis_history_stock_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_recommendation'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_mode'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_created_at'), table_name='analysis_history')
    op.drop_table('analysis_history')
    op.drop_index(op.f('ix_workstation_alerts_updated_at'), table_name='workstation_alerts')
    op.drop_index(op.f('ix_workstation_alerts_symbol'), table_name='workstation_alerts')
    op.drop_index(op.f('ix_workstation_alerts_status'), table_name='workstation_alerts')
    op.drop_index(op.f('ix_workstation_alerts_name'), table_name='workstation_alerts')
    op.drop_index(op.f('ix_workstation_alerts_id'), table_name='workstation_alerts')
    op.drop_index(op.f('ix_workstation_alerts_created_at'), table_name='workstation_alerts')
    op.drop_index(op.f('ix_workstation_alerts_alert_type'), table_name='workstation_alerts')
    op.drop_table('workstation_alerts')
    op.drop_index(op.f('ix_watched_stocks_symbol'), table_name='watched_stocks')
    op.drop_index(op.f('ix_watched_stocks_id'), table_name='watched_stocks')
    op.drop_index(op.f('ix_watched_stocks_created_at'), table_name='watched_stocks')
    op.drop_table('watched_stocks')
    op.drop_index(op.f('ix_system_logs_userId'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_symbol'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_source'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_orderId'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_module'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_error_hash'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_environment'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_correlationId'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('system_locks')
    op.drop_index(op.f('ix_strategy_performance_log_symbol'), table_name='strategy_performance_log')
    op.drop_index(op.f('ix_strategy_performance_log_screened_date'), table_name='strategy_performance_log')
    op.drop_index(op.f('ix_strategy_performance_log_id'), table_name='strategy_performance_log')
    op.drop_table('strategy_performance_log')
    op.drop_index(op.f('ix_service_health_updated_at'), table_name='service_health')
    op.drop_index(op.f('ix_service_health_created_at'), table_name='service_health')
    op.drop_table('service_health')
    op.drop_index(op.f('ix_scanner_sessions_updated_at'), table_name='scanner_sessions')
    op.drop_index(op.f('ix_scanner_sessions_created_at'), table_name='scanner_sessions')
    op.drop_table('scanner_sessions')
    op.drop_index(op.f('ix_scanned_candidates_symbol'), table_name='scanned_candidates')
    op.drop_index(op.f('ix_scanned_candidates_scanned_at'), table_name='scanned_candidates')
    op.drop_index(op.f('ix_scanned_candidates_id'), table_name='scanned_candidates')
    op.drop_table('scanned_candidates')
    op.drop_index(op.f('ix_scan_history_snapshots_universe'), table_name='scan_history_snapshots')
    op.drop_index(op.f('ix_scan_history_snapshots_scan_name'), table_name='scan_history_snapshots')
    op.drop_index(op.f('ix_scan_history_snapshots_mode'), table_name='scan_history_snapshots')
    op.drop_index(op.f('ix_scan_history_snapshots_id'), table_name='scan_history_snapshots')
    op.drop_index(op.f('ix_scan_history_snapshots_created_at'), table_name='scan_history_snapshots')
    op.drop_table('scan_history_snapshots')
    op.drop_index(op.f('ix_saved_scans_updated_at'), table_name='saved_scans')
    op.drop_index(op.f('ix_saved_scans_name'), table_name='saved_scans')
    op.drop_index(op.f('ix_saved_scans_id'), table_name='saved_scans')
    op.drop_index(op.f('ix_saved_scans_created_at'), table_name='saved_scans')
    op.drop_table('saved_scans')
    op.drop_index(op.f('ix_risk_settings_id'), table_name='risk_settings')
    op.drop_table('risk_settings')
    op.drop_index(op.f('ix_paper_trading_execution_events_updated_at'), table_name='paper_trading_execution_events')
    op.drop_index(op.f('ix_paper_trading_execution_events_symbol'), table_name='paper_trading_execution_events')
    op.drop_index(op.f('ix_paper_trading_execution_events_position_id'), table_name='paper_trading_execution_events')
    op.drop_index(op.f('ix_paper_trading_execution_events_order_id'), table_name='paper_trading_execution_events')
    op.drop_index(op.f('ix_paper_trading_execution_events_id'), table_name='paper_trading_execution_events')
    op.drop_index(op.f('ix_paper_trading_execution_events_event_type'), table_name='paper_trading_execution_events')
    op.drop_index(op.f('ix_paper_trading_execution_events_event_id'), table_name='paper_trading_execution_events')
    op.drop_index(op.f('ix_paper_trading_execution_events_dedupe_key'), table_name='paper_trading_execution_events')
    op.drop_index(op.f('ix_paper_trading_execution_events_created_at'), table_name='paper_trading_execution_events')
    op.drop_index('idx_execution_events_position_type', table_name='paper_trading_execution_events')
    op.drop_index('idx_execution_events_order_type', table_name='paper_trading_execution_events')
    op.drop_table('paper_trading_execution_events')
    op.drop_index(op.f('ix_paper_trading_accounts_updated_at'), table_name='paper_trading_accounts')
    op.drop_index(op.f('ix_paper_trading_accounts_id'), table_name='paper_trading_accounts')
    op.drop_index(op.f('ix_paper_trading_accounts_created_at'), table_name='paper_trading_accounts')
    op.drop_table('paper_trading_accounts')
    op.drop_index(op.f('ix_market_replay_sessions_updated_at'), table_name='market_replay_sessions')
    op.drop_index(op.f('ix_market_replay_sessions_status'), table_name='market_replay_sessions')
    op.drop_index(op.f('ix_market_replay_sessions_started_at'), table_name='market_replay_sessions')
    op.drop_index(op.f('ix_market_replay_sessions_replay_key'), table_name='market_replay_sessions')
    op.drop_index(op.f('ix_market_replay_sessions_id'), table_name='market_replay_sessions')
    op.drop_index(op.f('ix_market_replay_sessions_gap_start'), table_name='market_replay_sessions')
    op.drop_index(op.f('ix_market_replay_sessions_gap_end'), table_name='market_replay_sessions')
    op.drop_index(op.f('ix_market_replay_sessions_created_at'), table_name='market_replay_sessions')
    op.drop_table('market_replay_sessions')
    op.drop_index(op.f('ix_market_engine_sessions_updated_at'), table_name='market_engine_sessions')
    op.drop_index(op.f('ix_market_engine_sessions_trading_date'), table_name='market_engine_sessions')
    op.drop_index(op.f('ix_market_engine_sessions_status'), table_name='market_engine_sessions')
    op.drop_index(op.f('ix_market_engine_sessions_id'), table_name='market_engine_sessions')
    op.drop_index(op.f('ix_market_engine_sessions_created_at'), table_name='market_engine_sessions')
    op.drop_table('market_engine_sessions')
    op.drop_index(op.f('ix_latest_scan_results_updated_at'), table_name='latest_scan_results')
    op.drop_index(op.f('ix_latest_scan_results_scanned_at'), table_name='latest_scan_results')
    op.drop_index(op.f('ix_latest_scan_results_id'), table_name='latest_scan_results')
    op.drop_index(op.f('ix_latest_scan_results_created_at'), table_name='latest_scan_results')
    op.drop_table('latest_scan_results')
    op.drop_index(op.f('ix_historical_candles_updated_at'), table_name='historical_candles')
    op.drop_index(op.f('ix_historical_candles_timestamp'), table_name='historical_candles')
    op.drop_index(op.f('ix_historical_candles_symbol'), table_name='historical_candles')
    op.drop_index(op.f('ix_historical_candles_resolution'), table_name='historical_candles')
    op.drop_index(op.f('ix_historical_candles_id'), table_name='historical_candles')
    op.drop_index(op.f('ix_historical_candles_created_at'), table_name='historical_candles')
    op.drop_index('idx_hist_candles_sym_ts', table_name='historical_candles')
    op.drop_index('idx_hist_candles_sym_res_ts', table_name='historical_candles')
    op.drop_table('historical_candles')
    op.drop_index(op.f('ix_fyers_tokens_status'), table_name='fyers_tokens')
    op.drop_table('fyers_tokens')
    op.drop_table('fyers_token_history')
    op.drop_index(op.f('ix_dead_letter_jobs_id'), table_name='dead_letter_jobs')
    op.drop_index(op.f('ix_dead_letter_jobs_created_at'), table_name='dead_letter_jobs')
    op.drop_table('dead_letter_jobs')
    op.drop_index(op.f('ix_blacklisted_symbols_created_at'), table_name='blacklisted_symbols')
    op.drop_table('blacklisted_symbols')
    op.drop_index(op.f('ix_api_request_logs_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_created_at'), table_name='api_request_logs')
    op.drop_table('api_request_logs')
    # ### end Alembic commands ###
