"""migration_checkpoints

Revision ID: 86d16197228e
Revises: 7fa0ff0cccb8
Create Date: 2026-05-28 17:28:52.264199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d16197228e'
down_revision: Union[str, Sequence[str], None] = '7fa0ff0cccb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_checkpoints',
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('last_processed_primary_key', sa.Integer(), nullable=False),
    sa.Column('last_processed_chunk', sa.Integer(), nullable=False),
    sa.Column('rows_migrated', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('migration_status', sa.String(length=32), nullable=False),
    sa.Column('migration_run_id', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('table_name', name=op.f('pk_migration_checkpoints'))
    )
    op.create_index(op.f('ix_migration_checkpoints_table_name'), 'migration_checkpoints', ['table_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_migration_checkpoints_table_name'), table_name='migration_checkpoints')
    op.drop_table('migration_checkpoints')
    # ### end Alembic commands ###
