"""live_execution_foundation

Revision ID: 93945ca775e0
Revises: 6927db3b020a
Create Date: 2026-05-29 13:12:07.415772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93945ca775e0'
down_revision: Union[str, Sequence[str], None] = '6927db3b020a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_execution_logs',
    sa.Column('broker_trade_id', sa.String(length=128), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=False),
    sa.Column('execution_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('broker_trade_id', name=op.f('pk_broker_execution_logs'))
    )
    op.create_index(op.f('ix_broker_execution_logs_broker_order_id'), 'broker_execution_logs', ['broker_order_id'], unique=False)
    op.create_table('live_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_cash', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reserved_cash', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_risk_per_trade', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_cash >= 0', name=op.f('ck_live_accounts_check_available_cash_non_negative')),
    sa.CheckConstraint('reserved_cash >= 0', name=op.f('ck_live_accounts_check_reserved_cash_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_accounts'))
    )
    op.create_index(op.f('ix_live_accounts_created_at'), 'live_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_live_accounts_id'), 'live_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_live_accounts_updated_at'), 'live_accounts', ['updated_at'], unique=False)
    op.create_table('live_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=12), nullable=False),
    sa.Column('product_type', sa.String(length=8), nullable=False),
    sa.Column('requested_qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('filled_qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('order_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('broker_request_id', sa.String(length=64), nullable=True),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('reconciliation_attempts', sa.Integer(), nullable=False),
    sa.Column('next_reconcile_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_orders'))
    )
    op.create_index('idx_live_orders_reconciliation', 'live_orders', ['status', 'next_reconcile_at'], unique=False)
    op.create_index(op.f('ix_live_orders_account_id'), 'live_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_live_orders_broker_order_id'), 'live_orders', ['broker_order_id'], unique=True)
    op.create_index(op.f('ix_live_orders_broker_request_id'), 'live_orders', ['broker_request_id'], unique=True)
    op.create_index(op.f('ix_live_orders_created_at'), 'live_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_live_orders_execution_id'), 'live_orders', ['execution_id'], unique=True)
    op.create_index(op.f('ix_live_orders_id'), 'live_orders', ['id'], unique=False)
    op.create_index(op.f('ix_live_orders_idempotency_key'), 'live_orders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_live_orders_next_reconcile_at'), 'live_orders', ['next_reconcile_at'], unique=False)
    op.create_index(op.f('ix_live_orders_order_type'), 'live_orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_live_orders_side'), 'live_orders', ['side'], unique=False)
    op.create_index(op.f('ix_live_orders_status'), 'live_orders', ['status'], unique=False)
    op.create_index(op.f('ix_live_orders_symbol'), 'live_orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_live_orders_updated_at'), 'live_orders', ['updated_at'], unique=False)
    op.create_table('live_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_positions'))
    )
    op.create_index('idx_unique_live_open_position', 'live_positions', ['account_id', 'symbol'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_index(op.f('ix_live_positions_account_id'), 'live_positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_live_positions_created_at'), 'live_positions', ['created_at'], unique=False)
    op.create_index(op.f('ix_live_positions_id'), 'live_positions', ['id'], unique=False)
    op.create_index(op.f('ix_live_positions_status'), 'live_positions', ['status'], unique=False)
    op.create_index(op.f('ix_live_positions_symbol'), 'live_positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_live_positions_updated_at'), 'live_positions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_positions_updated_at'), table_name='live_positions')
    op.drop_index(op.f('ix_live_positions_symbol'), table_name='live_positions')
    op.drop_index(op.f('ix_live_positions_status'), table_name='live_positions')
    op.drop_index(op.f('ix_live_positions_id'), table_name='live_positions')
    op.drop_index(op.f('ix_live_positions_created_at'), table_name='live_positions')
    op.drop_index(op.f('ix_live_positions_account_id'), table_name='live_positions')
    op.drop_index('idx_unique_live_open_position', table_name='live_positions', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_table('live_positions')
    op.drop_index(op.f('ix_live_orders_updated_at'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_symbol'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_status'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_side'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_order_type'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_next_reconcile_at'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_idempotency_key'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_id'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_execution_id'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_created_at'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_broker_request_id'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_broker_order_id'), table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_account_id'), table_name='live_orders')
    op.drop_index('idx_live_orders_reconciliation', table_name='live_orders')
    op.drop_table('live_orders')
    op.drop_index(op.f('ix_live_accounts_updated_at'), table_name='live_accounts')
    op.drop_index(op.f('ix_live_accounts_id'), table_name='live_accounts')
    op.drop_index(op.f('ix_live_accounts_created_at'), table_name='live_accounts')
    op.drop_table('live_accounts')
    op.drop_index(op.f('ix_broker_execution_logs_broker_order_id'), table_name='broker_execution_logs')
    op.drop_table('broker_execution_logs')
    # ### end Alembic commands ###
