"""add_refresh_token_fields

Revision ID: beaf8450de15
Revises: 53fddb49fce8
Create Date: 2026-06-27 17:48:08.758615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beaf8450de15'
down_revision: Union[str, Sequence[str], None] = '53fddb49fce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fyers_tokens', sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fyers_tokens', sa.Column('last_auto_renewal_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fyers_tokens', sa.Column('last_auto_renewal_status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # WARNING: If refresh_token tracking columns contain data at the time of downgrade,
    # those values will be lost. The active access token remains intact, but the user
    # will need to re-enter their refresh token (and wait for an upgrade) to restore auto-renewal.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fyers_tokens', 'last_auto_renewal_status')
    op.drop_column('fyers_tokens', 'last_auto_renewal_at')
    op.drop_column('fyers_tokens', 'refresh_token_expires_at')
    # ### end Alembic commands ###
