import type { ScreenerResponse } from "./types";

export const sampleScreenerResponse: ScreenerResponse = {
  scanned_symbols: 500,
  screener_name: "Nifty 500 Combined Swing Scanner",
  data_valid_symbols: ["RELIANCE-EQ", "INFY-EQ", "TCS-EQ", "LT-EQ", "HDFCBANK-EQ", "ICICIBANK-EQ"],
  eligible_symbols: ["RELIANCE-EQ", "INFY-EQ", "TCS-EQ", "LT-EQ"],
  shortlisted_symbols: ["INFY-EQ", "RELIANCE-EQ", "TCS-EQ", "LT-EQ"],
  buy_candidate_symbols: ["INFY-EQ", "RELIANCE-EQ"],
  watch_candidate_symbols: ["TCS-EQ"],
  matched_symbols: ["INFY-EQ", "RELIANCE-EQ", "TCS-EQ", "LT-EQ"],
  matches: [
    {
      symbol: "INFY-EQ",
      close: 1642.15,
      ema_20: 1608.21,
      sma_30: 1598.4,
      sma_50: 1564.2,
      sma_100: 1492.6,
      sma_200: 1418.3,
      macd: 12.4,
      macd_signal: 9.1,
      supertrend: 1588.4,
      volume: 2145000,
      previous_volume: 1824000,
      screener_score: 84.2,
      technical_signal: "bullish",
      technical_score: 79.6,
      conditions: {
        broad_trend_eligibility: true,
        hard_filters_pass: true,
        close_above_ema20: true,
        supertrend_positive: true,
        macd_positive: true,
        volume_above_previous_day: true,
      },
      matched: true,
    },
    {
      symbol: "RELIANCE-EQ",
      close: 2938.8,
      ema_20: 2894.1,
      sma_30: 2881.2,
      sma_50: 2842.4,
      sma_100: 2764.9,
      sma_200: 2638.7,
      macd: 15.2,
      macd_signal: 11.8,
      supertrend: 2870.5,
      volume: 1542000,
      previous_volume: 1390000,
      screener_score: 80.4,
      technical_signal: "bullish",
      technical_score: 77.1,
      conditions: {
        broad_trend_eligibility: true,
        hard_filters_pass: true,
        close_above_ema20: true,
        supertrend_positive: true,
        macd_positive: true,
        volume_above_previous_day: true,
      },
      matched: true,
    },
    {
      symbol: "TCS-EQ",
      close: 4188.2,
      ema_20: 4155.2,
      sma_30: 4108.9,
      sma_50: 4066.3,
      sma_100: 3971.2,
      sma_200: 3848.7,
      macd: 8.1,
      macd_signal: 7.4,
      supertrend: 4118.8,
      volume: 844200,
      previous_volume: 838100,
      screener_score: 72.8,
      technical_signal: "neutral",
      technical_score: 66.5,
      conditions: {
        broad_trend_eligibility: true,
        hard_filters_pass: true,
        close_above_ema20: true,
        supertrend_positive: true,
        macd_positive: true,
        volume_above_previous_day: true,
      },
      matched: true,
    },
    {
      symbol: "LT-EQ",
      close: 3778.5,
      ema_20: 3720.3,
      sma_30: 3688.1,
      sma_50: 3624.4,
      sma_100: 3482.6,
      sma_200: 3310.5,
      macd: 5.7,
      macd_signal: 5.4,
      supertrend: 3694.1,
      volume: 611200,
      previous_volume: 590100,
      screener_score: 68.9,
      technical_signal: "neutral",
      technical_score: 63.9,
      conditions: {
        broad_trend_eligibility: true,
        hard_filters_pass: true,
        close_above_ema20: true,
        supertrend_positive: true,
        macd_positive: true,
        volume_above_previous_day: true,
      },
      matched: true,
    },
  ],
  analysis: {
    generated_at: "2026-04-11T10:43:55.000Z",
    disclaimer: "Advisory only. Not financial advice.",
    rankings: {
      rankings: [
        { rank: 1, symbol: "INFY-EQ", overall_score: 92.6, recommendation: "BUY", best_for_mode: "swing" },
        { rank: 2, symbol: "RELIANCE-EQ", overall_score: 89.8, recommendation: "BUY", best_for_mode: "swing" },
        { rank: 3, symbol: "TCS-EQ", overall_score: 74.3, recommendation: "WATCH", best_for_mode: "swing" },
      ],
      buy_rankings: [
        { rank: 1, symbol: "INFY-EQ", overall_score: 92.6, recommendation: "BUY", best_for_mode: "swing" },
        { rank: 2, symbol: "RELIANCE-EQ", overall_score: 89.8, recommendation: "BUY", best_for_mode: "swing" },
      ],
      watch_rankings: [
        { rank: 3, symbol: "TCS-EQ", overall_score: 74.3, recommendation: "WATCH", best_for_mode: "swing" },
      ],
      best_intraday_candidate: null,
      best_swing_candidate: "INFY-EQ",
      disclaimer: "Advisory only.",
    },
    items: [
      {
        symbol: "INFY-EQ",
        disclaimer: "Advisory only.",
        news_summary: "News tone is mildly supportive, with IT spending commentary helping the swing setup.",
        news_sentiment_label: "positive",
        news_sentiment_score: 0.63,
        ohlcv: [
          { timestamp: "2026-03-25T00:00:00Z", open: 1575, high: 1588, low: 1568, close: 1584, volume: 1223000 },
          { timestamp: "2026-03-26T00:00:00Z", open: 1586, high: 1598, low: 1579, close: 1594, volume: 1173000 },
          { timestamp: "2026-03-27T00:00:00Z", open: 1592, high: 1605, low: 1588, close: 1602, volume: 1268000 },
          { timestamp: "2026-03-30T00:00:00Z", open: 1603, high: 1618, low: 1596, close: 1610, volume: 1352000 },
          { timestamp: "2026-03-31T00:00:00Z", open: 1612, high: 1620, low: 1604, close: 1617, volume: 1441000 },
          { timestamp: "2026-04-01T00:00:00Z", open: 1618, high: 1628, low: 1611, close: 1622, volume: 1504000 },
          { timestamp: "2026-04-02T00:00:00Z", open: 1620, high: 1634, low: 1618, close: 1630, volume: 1684000 },
          { timestamp: "2026-04-03T00:00:00Z", open: 1631, high: 1646, low: 1627, close: 1640, volume: 1876000 },
          { timestamp: "2026-04-06T00:00:00Z", open: 1638, high: 1648, low: 1634, close: 1644, volume: 1943000 },
          { timestamp: "2026-04-07T00:00:00Z", open: 1640, high: 1650, low: 1635, close: 1642.15, volume: 2145000 },
        ],
        technical: [
          {
            mode: "swing",
            signal: "bullish",
            score: 79.6,
            summary: "INFY-EQ shows a bullish swing setup with trend, momentum, and liquidity filters all passing.",
            indicators: {
              ema_20: 1608.21,
              sma_20: 1604.4,
              sma_30: 1598.4,
              sma_50: 1564.2,
              sma_100: 1492.6,
              sma_200: 1418.3,
              rsi_14: 61.2,
              macd: 12.4,
              macd_signal: 9.1,
              supertrend: 1588.4,
              higher_timeframe_trend: "uptrend",
              close_above_ema20: true,
              supertrend_positive: true,
              macd_positive: true,
              rsi_supportive: true,
              rsi_in_buy_zone: true,
              sma_uptrend_20d: true,
              hh_hl_2d: true,
              hh_hl_3d: true,
              hh_hl_4d: false,
              latest_confirms_5d_structure: true,
              structure_score: 3,
              structure_supportive: true,
              hammer_or_gravestone: false,
              volume_above_50000: true,
              volume_above_previous_day: true,
              price_above_100: true,
              price_below_500000: true,
              core_trend_filter_pass: true,
              core_momentum_filter_pass: true,
              basic_liquidity_filter_pass: true,
              hard_filters_pass: true,
            },
          },
        ],
        news_articles: [
          {
            title: "Infosys gains as enterprise demand commentary stays stable",
            description: "Broker commentary suggests the IT spending environment is steady for large caps.",
            source: "Market Wire",
            url: "https://example.com/infy-1",
            published_at: "2026-04-10T08:00:00Z",
            sentiment_score: 0.61,
          },
          {
            title: "Rupee softness keeps exporters in focus",
            description: "Export-oriented technology companies remain supported by currency trends.",
            source: "Business Feed",
            url: "https://example.com/infy-2",
            published_at: "2026-04-10T06:30:00Z",
            sentiment_score: 0.58,
          },
        ],
        backtests: [
          {
            mode: "swing",
            strategy_name: "Trend pullback",
            total_return: 18.2,
            cagr: 12.4,
            max_drawdown: 6.9,
            win_rate: 62.1,
            profit_factor: 1.81,
            trade_count: 14,
            verdict: "strong",
            equity_curve: [
              { label: "T1", equity: 100000 },
              { label: "T2", equity: 101800 },
              { label: "T3", equity: 103200 },
              { label: "T4", equity: 106100 },
              { label: "T5", equity: 109400 },
            ],
          },
        ],
        recommendation: {
          action: "BUY",
          confidence: 0.82,
          score: 92.6,
          summary: "BUY because hard filters are intact, structure is supportive, and backtest support remains strong.",
          reasoning: {
            bullets: [
              "Trend and momentum hard filters are passing cleanly.",
              "Recent price structure still supports a multi-session continuation move.",
              "Backtest profile is strong enough to justify active attention.",
            ],
            risk_factors: ["A weak close back under EMA 20 would reduce setup quality."],
            invalidation_signals: ["Exit if price closes below 1608 and loses follow-through volume."],
          },
          trade_plans: [
            {
              mode: "swing",
              strategy_name: "Trend pullback",
              setup_type: "pullback continuation",
              timeframe: "2 to 5 sessions",
              bias: "long",
              entry_low: 1636,
              entry_high: 1644,
              stop_loss: 1608,
              target_1: 1678,
              target_2: 1702,
              target_3: 1728,
              risk_reward_ratio: 1.6,
              notes: "Prefer entries near the lower half of the zone if volume stays healthy.",
            },
          ],
        },
      },
      {
        symbol: "RELIANCE-EQ",
        disclaimer: "Advisory only.",
        news_summary: "Energy and retail commentary are supportive, keeping the swing setup constructive.",
        news_sentiment_label: "positive",
        news_sentiment_score: 0.48,
        ohlcv: [
          { timestamp: "2026-04-01T00:00:00Z", open: 2874, high: 2894, low: 2862, close: 2888, volume: 1200000 },
          { timestamp: "2026-04-02T00:00:00Z", open: 2888, high: 2908, low: 2880, close: 2898, volume: 1250000 },
          { timestamp: "2026-04-03T00:00:00Z", open: 2896, high: 2920, low: 2890, close: 2915, volume: 1310000 },
          { timestamp: "2026-04-04T00:00:00Z", open: 2914, high: 2936, low: 2908, close: 2928, volume: 1498000 },
          { timestamp: "2026-04-07T00:00:00Z", open: 2924, high: 2942, low: 2912, close: 2938.8, volume: 1542000 },
        ],
        technical: [
          {
            mode: "swing",
            signal: "bullish",
            score: 77.1,
            summary: "RELIANCE-EQ shows a bullish swing setup with strong trend alignment and acceptable structure support.",
            indicators: {
              ema_20: 2894.1,
              sma_20: 2888.1,
              sma_30: 2881.2,
              sma_50: 2842.4,
              sma_100: 2764.9,
              sma_200: 2638.7,
              rsi_14: 58.7,
              macd: 15.2,
              macd_signal: 11.8,
              supertrend: 2870.5,
              higher_timeframe_trend: "uptrend",
              close_above_ema20: true,
              supertrend_positive: true,
              macd_positive: true,
              rsi_supportive: true,
              rsi_in_buy_zone: true,
              sma_uptrend_20d: true,
              structure_score: 2,
              structure_supportive: true,
              core_trend_filter_pass: true,
              core_momentum_filter_pass: true,
              basic_liquidity_filter_pass: true,
              hard_filters_pass: true,
            },
          },
        ],
        news_articles: [],
        backtests: [
          {
            mode: "swing",
            strategy_name: "Trend continuation",
            total_return: 15.1,
            cagr: 10.1,
            max_drawdown: 7.4,
            win_rate: 58.4,
            profit_factor: 1.56,
            trade_count: 11,
            verdict: "acceptable",
            equity_curve: [
              { label: "T1", equity: 100000 },
              { label: "T2", equity: 100900 },
              { label: "T3", equity: 102300 },
              { label: "T4", equity: 104600 },
            ],
          },
        ],
        recommendation: {
          action: "BUY",
          confidence: 0.78,
          score: 89.8,
          summary: "BUY because the stock remains in trend and the backtest profile is still acceptable for swing continuation.",
          reasoning: {
            bullets: ["Trend structure and liquidity remain supportive.", "Momentum is positive without being overstretched."],
            risk_factors: ["A failed breakout above recent highs could delay the move."],
            invalidation_signals: ["Exit if price closes below 2894 with weakening volume."],
          },
          trade_plans: [
            {
              mode: "swing",
              strategy_name: "Trend continuation",
              setup_type: "breakout continuation",
              timeframe: "3 to 6 sessions",
              bias: "long",
              entry_low: 2922,
              entry_high: 2940,
              stop_loss: 2894,
              target_1: 2974,
              target_2: 3008,
              target_3: 3040,
              risk_reward_ratio: 1.65,
              notes: "Best used on continued strength above the recent range.",
            },
          ],
        },
      },
      {
        symbol: "TCS-EQ",
        disclaimer: "Advisory only.",
        news_summary: "News is neutral, so the setup still needs more confirmation.",
        news_sentiment_label: "neutral",
        news_sentiment_score: 0.12,
        ohlcv: [
          { timestamp: "2026-04-01T00:00:00Z", open: 4110, high: 4144, low: 4098, close: 4136, volume: 760000 },
          { timestamp: "2026-04-02T00:00:00Z", open: 4138, high: 4162, low: 4128, close: 4154, volume: 803000 },
          { timestamp: "2026-04-03T00:00:00Z", open: 4155, high: 4184, low: 4146, close: 4178, volume: 829000 },
          { timestamp: "2026-04-04T00:00:00Z", open: 4176, high: 4198, low: 4162, close: 4188.2, volume: 844200 },
        ],
        technical: [
          {
            mode: "swing",
            signal: "neutral",
            score: 66.5,
            summary: "TCS-EQ keeps the hard filters intact, but the structure quality is less convincing than the top BUY names.",
            indicators: {
              ema_20: 4155.2,
              sma_20: 4122.1,
              sma_30: 4108.9,
              sma_50: 4066.3,
              sma_100: 3971.2,
              sma_200: 3848.7,
              rsi_14: 55.4,
              macd: 8.1,
              macd_signal: 7.4,
              supertrend: 4118.8,
              higher_timeframe_trend: "uptrend",
              close_above_ema20: true,
              supertrend_positive: true,
              macd_positive: true,
              rsi_supportive: true,
              rsi_in_buy_zone: true,
              structure_score: 1,
              structure_supportive: false,
              core_trend_filter_pass: true,
              core_momentum_filter_pass: true,
              basic_liquidity_filter_pass: true,
              hard_filters_pass: true,
            },
          },
        ],
        news_articles: [],
        backtests: [
          {
            mode: "swing",
            strategy_name: "Trend continuation",
            total_return: 9.2,
            cagr: 6.4,
            max_drawdown: 8.9,
            win_rate: 52.8,
            profit_factor: 1.28,
            trade_count: 10,
            verdict: "acceptable",
            equity_curve: [
              { label: "T1", equity: 100000 },
              { label: "T2", equity: 100600 },
              { label: "T3", equity: 101000 },
              { label: "T4", equity: 102100 },
            ],
          },
        ],
        recommendation: {
          action: "WATCH",
          confidence: 0.62,
          score: 74.3,
          summary: "WATCH because the trend is intact, but structure and news support are not yet strong enough for BUY.",
          reasoning: {
            bullets: ["Hard filters are still intact.", "Structure support is weaker than the top two names."],
            risk_factors: ["A lack of fresh volume can stall the setup."],
            invalidation_signals: ["Avoid if price loses EMA 20 and closes weakly below 4155."],
          },
          trade_plans: [
            {
              mode: "swing",
              strategy_name: "Trend continuation",
              setup_type: "watch for breakout",
              timeframe: "2 to 4 sessions",
              bias: "wait",
              entry_low: 4190,
              entry_high: 4206,
              stop_loss: 4155,
              target_1: 4248,
              target_2: 4282,
              target_3: 4314,
              risk_reward_ratio: 1.42,
              notes: "Wait for a cleaner breakout confirmation before taking size.",
            },
          ],
        },
      },
    ],
  },
  disclaimer: "Advisory only. Not financial advice.",
};
